name: 构建 java21

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 */3 * *"

jobs:
  build_android:
    strategy:
      matrix:
        arch: [ "aarch32", "aarch64", "x86", "x86_64" ]
      fail-fast: false

    name: "构建 java ${{matrix.arch}}"
    runs-on: ubuntu-24.04
    steps:
    - name: 检出代码库
      uses: actions/checkout@v4.1.4

    - name: 设置 JDK 21
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 21
        distribution: temurin

    - name: 安装构建依赖
      run: |
        sudo apt update
        sudo apt -y install systemtap-sdt-dev libxtst-dev libasound2-dev libelf-dev libfontconfig1-dev libx11-dev libxext-dev libxrandr-dev libxrender-dev libxtst-dev libxt-dev
        git clone --depth 1 --branch buildjre21 https://github.com/Vera-Firefly/android-openjdk-build

    - name: 使用 CI 构建脚本进行构建
      run: |
        cd android-openjdk-build
        bash "ci_build_arch_${{matrix.arch}}.sh"

    - name: 上传 JDK 构建输出
      uses: actions/upload-artifact@v4.3.3
      with:
        name: "jdk21-${{matrix.arch}}"
        path: android-openjdk-build/jdk21*.tar.xz

    - name: 上传 JRE 构建输出
      uses: actions/upload-artifact@v4.3.3
      with:
        name: 'jre21-${{matrix.arch}}'
        path: android-openjdk-build/jre21*.tar.xz

    - name: 创建 Release 并上传 JDK/JRE 构建文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="java21-${{matrix.arch}}-$(date +'%Y%m%d%H%M%S')"
        RELEASE_NAME="Java 21 Build - ${{matrix.arch}}"
        RELEASE_BODY="Automated build of Java 21 for ${{matrix.arch}}."
        
        # Create a new release
        gh release create $TAG_NAME \
          --title "$RELEASE_NAME" \
          --notes "$RELEASE_BODY" \
          --target "$(git rev-parse HEAD)" \
          android-openjdk-build/jdk21*.tar.xz \
          android-openjdk-build/jre21*.tar.xz

    - name: 清理构建目录
      run: |
        rm -rf android-openjdk-build

      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KEY_PASSWORD: ${{ secrets.SSH_KEY_PASSWORD }}
        USER_EMAIL: ${{ secrets.USER_EMAIL }}
        USER_NAME: ${{ secrets.USER_NAME }}
